export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    REMOVE_SET_PRODUCTS : "REMOVE_SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    SET_GENDER : "SET_GENDER",
    SET_CATEGORY : "SET_CATEGORY",
    SET_BRAND : "SET_BRAND",
    SET_PRICE : "SET_PRICE",
    REMOVE_FILTERS : "REMOVE_FILTERS",
}